// Initial Synthetic Workspace & Local Seed Datasets

import { Project, User, Team, DataSource, AuditEvent, TaskItem } from '../../types/domain';
import { Pipeline } from '../../types/pipeline';
import { Topic, ConsumerGroup } from '../../types/streaming';
import { SchemaRegistryEntry, Dataset, DataContract, QualityCheckSuite } from '../../types/quality';
import { MLFeatureSet, MLDataset, JobSchedule } from '../../types/ml';
import { AlertRule, SystemAlert } from '../../types/observability';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Alex Mercer',
    email: 'alex.mercer@datastream.local',
    role: 'Data Engineer',
    department: 'Data Platform',
    status: 'active',
    createdAt: '2026-01-15T08:00:00Z',
    updatedAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'usr-2',
    name: 'Elena Rostova',
    email: 'elena.r@datastream.local',
    role: 'Game Analyst',
    department: 'Player Analytics',
    status: 'active',
    createdAt: '2026-01-16T09:30:00Z',
    updatedAt: '2026-01-16T09:30:00Z',
  },
  {
    id: 'usr-3',
    name: 'Marcus Chen',
    email: 'marcus.c@datastream.local',
    role: 'ML Engineer',
    department: 'AI Systems',
    status: 'active',
    createdAt: '2026-01-20T11:15:00Z',
    updatedAt: '2026-01-20T11:15:00Z',
  },
  {
    id: 'usr-4',
    name: 'Sarah Jenkins',
    email: 'sarah.j@datastream.local',
    role: 'Administrator',
    department: 'Infrastructure',
    status: 'active',
    createdAt: '2026-01-10T07:00:00Z',
    updatedAt: '2026-01-10T07:00:00Z',
  },
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'team-1',
    name: 'Core Data Infra',
    description: 'Maintains real-time streaming, topics, and DAG pipeline engine',
    members: [
      { userId: 'usr-1', role: 'Data Engineer', joinedAt: '2026-01-15T08:00:00Z' },
      { userId: 'usr-4', role: 'Administrator', joinedAt: '2026-01-10T07:00:00Z' },
    ],
    projectCount: 3,
    createdAt: '2026-01-15T08:00:00Z',
    updatedAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'team-2',
    name: 'Game Telemetry & ML',
    description: 'Player cohort analytics, economy flows, and ML feature store',
    members: [
      { userId: 'usr-2', role: 'Game Analyst', joinedAt: '2026-01-16T09:30:00Z' },
      { userId: 'usr-3', role: 'ML Engineer', joinedAt: '2026-01-20T11:15:00Z' },
    ],
    projectCount: 2,
    createdAt: '2026-01-16T09:30:00Z',
    updatedAt: '2026-01-16T09:30:00Z',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-nexus-game',
    name: 'Nexus Game Telemetry Pipeline',
    slug: 'nexus-game-telemetry',
    description: 'Real-time player event streaming, session aggregation, and economy fraud detection.',
    ownerId: 'usr-1',
    teamId: 'team-2',
    status: 'active',
    tags: ['Gaming', 'Streaming', 'RealTime', 'ML'],
    settings: {
      defaultStorageRetentionDays: 30,
      enableQualityAlerts: true,
      maxStreamThroughputMsgPerSec: 5000,
      watermarkLatenessMs: 5000,
      autoSaveIntervalMs: 10000,
    },
    stats: {
      sourcesCount: 4,
      pipelinesCount: 3,
      datasetsCount: 5,
      activeJobsCount: 2,
      totalRecordsProcessed: 1482090,
      avgLatencyMs: 42,
      qualityScorePct: 98.4,
    },
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-28T16:45:00Z',
  },
  {
    id: 'proj-financial-stream',
    name: 'Real-Time Financial Audit',
    slug: 'financial-audit-stream',
    description: 'Ingests transaction streams, runs windowed aggregate checks, and alerts on anomaly thresholds.',
    ownerId: 'usr-1',
    teamId: 'team-1',
    status: 'active',
    tags: ['Finance', 'Batch', 'Audit', 'SLAs'],
    settings: {
      defaultStorageRetentionDays: 90,
      enableQualityAlerts: true,
      maxStreamThroughputMsgPerSec: 10000,
      watermarkLatenessMs: 2000,
      autoSaveIntervalMs: 5000,
    },
    stats: {
      sourcesCount: 3,
      pipelinesCount: 2,
      datasetsCount: 4,
      activeJobsCount: 1,
      totalRecordsProcessed: 3209410,
      avgLatencyMs: 28,
      qualityScorePct: 99.8,
    },
    createdAt: '2026-02-10T12:00:00Z',
    updatedAt: '2026-02-27T11:20:00Z',
  },
];

export const INITIAL_DATA_SOURCES: DataSource[] = [
  {
    id: 'src-game-events',
    projectId: 'proj-nexus-game',
    name: 'Game Client Live Telemetry',
    type: 'Game Telemetry',
    status: 'active',
    description: 'Real-time player actions, match results, and session durations',
    config: {
      eventRatePerSec: 250,
      generatorSeed: 42,
      autoSchemaDetect: true,
    },
    schemaId: 'sch-game-event',
    recordCount: 840200,
    lastIngestedAt: '2026-08-31T23:50:00Z',
    eventRate: 250,
    bytesSize: 154200300,
    createdAt: '2026-02-01T10:30:00Z',
    updatedAt: '2026-08-31T23:50:00Z',
  },
  {
    id: 'src-player-profile-batch',
    projectId: 'proj-nexus-game',
    name: 'Player Profiles Catalog (CSV)',
    type: 'CSV',
    status: 'active',
    description: 'Demographics, registered regions, and current VIP status',
    config: {
      delimiter: ',',
      hasHeader: true,
    },
    schemaId: 'sch-player-profile',
    recordCount: 50000,
    lastIngestedAt: '2026-08-30T14:00:00Z',
    eventRate: 0,
    bytesSize: 8400120,
    createdAt: '2026-02-02T11:00:00Z',
    updatedAt: '2026-08-30T14:00:00Z',
  },
  {
    id: 'src-economy-log',
    projectId: 'proj-nexus-game',
    name: 'In-Game Store Transactions',
    type: 'NDJSON',
    status: 'active',
    description: 'Gem and gold purchases, item unlocks, and currency balances',
    config: {
      eventRatePerSec: 45,
    },
    schemaId: 'sch-economy-event',
    recordCount: 192000,
    lastIngestedAt: '2026-08-31T23:55:00Z',
    eventRate: 45,
    bytesSize: 34102900,
    createdAt: '2026-02-05T09:00:00Z',
    updatedAt: '2026-08-31T23:55:00Z',
  },
];

export const INITIAL_PIPELINES: Pipeline[] = [
  {
    id: 'pipe-player-session-agg',
    projectId: 'proj-nexus-game',
    name: 'Player Session & Churn Predictor Pipeline',
    description: 'Joins live player match events with demographic profiles, runs 5-minute tumbling windows, and outputs feature matrices.',
    status: 'running',
    currentVersion: 2,
    nodes: [
      {
        id: 'node-1',
        type: 'Source',
        label: 'Game Telemetry Source',
        position: { x: 80, y: 150 },
        config: {},
        inputs: [],
        outputs: ['edge-1'],
        status: 'running',
        executionMetrics: { recordsIn: 2500, recordsOut: 2500, recordsDropped: 0, processingTimeMs: 12 },
      },
      {
        id: 'node-2',
        type: 'Filter',
        label: 'Filter Valid Events',
        position: { x: 300, y: 150 },
        config: { filterExpression: "event_name != 'error_logged' AND player_id IS NOT NULL" },
        inputs: ['edge-1'],
        outputs: ['edge-2'],
        status: 'running',
        executionMetrics: { recordsIn: 2500, recordsOut: 2480, recordsDropped: 20, processingTimeMs: 18 },
      },
      {
        id: 'node-3',
        type: 'Window',
        label: '5-Min Tumbling Window',
        position: { x: 520, y: 150 },
        config: { windowType: 'tumbling', windowSizeSeconds: 300, timestampField: 'timestamp' },
        inputs: ['edge-2'],
        outputs: ['edge-3'],
        status: 'running',
        executionMetrics: { recordsIn: 2480, recordsOut: 2480, recordsDropped: 0, processingTimeMs: 25 },
      },
      {
        id: 'node-4',
        type: 'Aggregate',
        label: 'Player Engagement Aggregator',
        position: { x: 740, y: 150 },
        config: {
          groupByFields: ['player_id'],
          aggregations: [
            { field: 'session_id', op: 'count', alias: 'session_count' },
            { field: 'duration_seconds', op: 'avg', alias: 'avg_duration' },
            { field: 'score', op: 'sum', alias: 'total_score' },
          ],
        },
        inputs: ['edge-3'],
        outputs: ['edge-4'],
        status: 'running',
        executionMetrics: { recordsIn: 2480, recordsOut: 450, recordsDropped: 0, processingTimeMs: 34 },
      },
      {
        id: 'node-5',
        type: 'Quality Check',
        label: 'Quality Score & Contract Gate',
        position: { x: 960, y: 150 },
        config: { rejectAction: 'quarantine' },
        inputs: ['edge-4'],
        outputs: ['edge-5'],
        status: 'running',
        executionMetrics: { recordsIn: 450, recordsOut: 450, recordsDropped: 0, processingTimeMs: 8 },
      },
      {
        id: 'node-6',
        type: 'Output',
        label: 'ML Feature Set Sink',
        position: { x: 1180, y: 150 },
        config: { outputDatasetId: 'ds-player-features' },
        inputs: ['edge-5'],
        outputs: [],
        status: 'completed',
        executionMetrics: { recordsIn: 450, recordsOut: 450, recordsDropped: 0, processingTimeMs: 5 },
      },
    ],
    edges: [
      { id: 'edge-1', sourceNodeId: 'node-1', targetNodeId: 'node-2' },
      { id: 'edge-2', sourceNodeId: 'node-2', targetNodeId: 'node-3' },
      { id: 'edge-3', sourceNodeId: 'node-3', targetNodeId: 'node-4' },
      { id: 'edge-4', sourceNodeId: 'node-4', targetNodeId: 'node-5' },
      { id: 'edge-5', sourceNodeId: 'node-5', targetNodeId: 'node-6' },
    ],
    parameters: [
      { name: 'WINDOW_SIZE_SEC', type: 'number', defaultValue: '300', description: 'Aggregation window size in seconds' },
    ],
    versions: [
      { versionNumber: 1, publishedAt: '2026-02-15T10:00:00Z', authorId: 'usr-1', nodes: [], edges: [], changeDescription: 'Initial draft version' },
      { versionNumber: 2, publishedAt: '2026-02-25T14:30:00Z', authorId: 'usr-1', nodes: [], edges: [], changeDescription: 'Added quality check gate node' },
    ],
    lastRunId: 'run-101',
    lastRunStatus: 'Succeeded',
    lastRunAt: '2026-08-31T23:45:00Z',
    tags: ['Live', 'Windowed', 'MLSink'],
    scheduleCron: '*/5 * * * *',
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-08-31T23:45:00Z',
  },
];

export const INITIAL_TOPICS: Topic[] = [
  {
    id: 'top-player-events',
    projectId: 'proj-nexus-game',
    name: 'player-events',
    description: 'Raw inbound telemetry events from game clients',
    partitionsCount: 4,
    totalEvents: 1420900,
    throughputMsgPerSec: 250,
    retentionHours: 72,
    status: 'active',
    partitions: [
      { partitionId: 0, currentOffset: 355225, recordCount: 355225, throughputMsgPerSec: 62.5, consumerLag: 12, sizeBytes: 38400000 },
      { partitionId: 1, currentOffset: 355225, recordCount: 355225, throughputMsgPerSec: 62.5, consumerLag: 8, sizeBytes: 38400000 },
      { partitionId: 2, currentOffset: 355225, recordCount: 355225, throughputMsgPerSec: 62.5, consumerLag: 15, sizeBytes: 38400000 },
      { partitionId: 3, currentOffset: 355225, recordCount: 355225, throughputMsgPerSec: 62.5, consumerLag: 5, sizeBytes: 38400000 },
    ],
    createdAt: '2026-02-01T10:30:00Z',
    updatedAt: '2026-08-31T23:55:00Z',
  },
  {
    id: 'top-economy-events',
    projectId: 'proj-nexus-game',
    name: 'economy-events',
    description: 'Store purchases, gem unlocks, and currency transactions',
    partitionsCount: 2,
    totalEvents: 310400,
    throughputMsgPerSec: 45,
    retentionHours: 168,
    status: 'active',
    partitions: [
      { partitionId: 0, currentOffset: 155200, recordCount: 155200, throughputMsgPerSec: 22.5, consumerLag: 2, sizeBytes: 17000000 },
      { partitionId: 1, currentOffset: 155200, recordCount: 155200, throughputMsgPerSec: 22.5, consumerLag: 4, sizeBytes: 17000000 },
    ],
    createdAt: '2026-02-05T09:00:00Z',
    updatedAt: '2026-08-31T23:55:00Z',
  },
];

export const INITIAL_CONSUMER_GROUPS: ConsumerGroup[] = [
  {
    id: 'cg-session-aggregator',
    projectId: 'proj-nexus-game',
    name: 'cg-session-aggregator',
    topicName: 'player-events',
    totalLag: 40,
    processingRateMsgPerSec: 248,
    status: 'active',
    members: [
      { consumerId: 'c-worker-1', consumerName: 'session-worker-0', assignedPartitions: [0, 1] },
      { consumerId: 'c-worker-2', consumerName: 'session-worker-1', assignedPartitions: [2, 3] },
    ],
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-08-31T23:55:00Z',
  },
];

export const INITIAL_SCHEMAS: SchemaRegistryEntry[] = [
  {
    id: 'sch-game-event',
    projectId: 'proj-nexus-game',
    name: 'GameTelemetryEvent',
    description: 'Schema for player actions, quest events, and level ups',
    currentVersion: 3,
    compatibilityMode: 'BACKWARD',
    fields: [
      { name: 'event_id', type: 'String', constraint: { required: true }, isPrimaryKey: true },
      { name: 'player_id', type: 'String', constraint: { required: true } },
      { name: 'event_name', type: 'String', constraint: { required: true } },
      { name: 'timestamp', type: 'Datetime', constraint: { required: true } },
      { name: 'properties', type: 'Object', constraint: { required: false } },
    ],
    versions: [
      { versionNumber: 1, createdAt: '2026-02-01T10:00:00Z', author: 'Alex Mercer', fields: [], compatibility: 'Compatible', changeNotes: 'Initial v1 schema' },
      { versionNumber: 2, createdAt: '2026-02-15T12:00:00Z', author: 'Alex Mercer', fields: [], compatibility: 'Compatible', changeNotes: 'Added properties object' },
      { versionNumber: 3, createdAt: '2026-02-28T09:00:00Z', author: 'Elena Rostova', fields: [], compatibility: 'Compatible', changeNotes: 'Made timestamp strict datetime' },
    ],
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-28T09:00:00Z',
  },
];

export const INITIAL_DATASETS: Dataset[] = [
  {
    id: 'ds-player-features',
    projectId: 'proj-nexus-game',
    name: 'Aggregated Player Features (7D)',
    description: 'Rolling 7-day player engagement, total score, and session frequency metrics',
    ownerId: 'usr-1',
    ownerName: 'Alex Mercer',
    schemaId: 'sch-game-event',
    version: 1,
    recordCount: 14500,
    sizeBytes: 4200000,
    qualityScorePct: 99.2,
    freshnessMinutesAgo: 4,
    sourcePipelineId: 'pipe-player-session-agg',
    columns: [
      { name: 'player_id', type: 'String', nullable: false, description: 'Unique player key' },
      { name: 'session_count', type: 'Integer', nullable: false, description: 'Total sessions in 7 days' },
      { name: 'avg_duration', type: 'Float', nullable: false, description: 'Average session duration in seconds' },
      { name: 'total_score', type: 'Integer', nullable: false, description: 'Accumulated match score' },
      { name: 'churn_risk_tier', type: 'String', nullable: true, description: 'ML predicted churn risk (Low/Med/High)' },
    ],
    tags: ['MLReady', 'Clean', 'Production'],
    createdAt: '2026-02-15T12:00:00Z',
    updatedAt: '2026-08-31T23:50:00Z',
  },
];

export const INITIAL_CONTRACTS: DataContract[] = [
  {
    id: 'ct-player-features-sla',
    projectId: 'proj-nexus-game',
    name: 'Player Features 99.0% Quality SLA',
    datasetId: 'ds-player-features',
    datasetName: 'Aggregated Player Features (7D)',
    ownerName: 'Alex Mercer',
    slaMaxLatencyMinutes: 15,
    minQualityScorePct: 98.0,
    maxNullPct: 1.0,
    schemaId: 'sch-game-event',
    status: 'compliant',
    lastCheckedAt: '2026-08-31T23:50:00Z',
    activeViolationsCount: 0,
    createdAt: '2026-02-20T10:00:00Z',
    updatedAt: '2026-08-31T23:50:00Z',
  },
];

export const INITIAL_ALERT_RULES: AlertRule[] = [
  {
    id: 'alt-rule-latency',
    projectId: 'proj-nexus-game',
    name: 'High Processing Latency Alert',
    type: 'High Latency',
    description: 'Triggers when average pipeline processing latency exceeds 100ms',
    metricField: 'avgLatencyMs',
    operator: '>',
    thresholdValue: 100,
    evaluationWindowMinutes: 5,
    severity: 'high',
    enabled: true,
    notificationChannels: ['Local Desktop Toast', 'System Alert Center'],
    lastTriggeredAt: undefined,
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-10T10:00:00Z',
  },
  {
    id: 'alt-rule-quality',
    projectId: 'proj-nexus-game',
    name: 'Data Quality Breach Warning',
    type: 'Quality Below Threshold',
    description: 'Triggers when quality check score drops below 95%',
    metricField: 'qualityScorePct',
    operator: '<',
    thresholdValue: 95,
    evaluationWindowMinutes: 10,
    severity: 'critical',
    enabled: true,
    notificationChannels: ['Local Desktop Toast', 'Audit Log'],
    lastTriggeredAt: undefined,
    createdAt: '2026-02-15T11:00:00Z',
    updatedAt: '2026-02-15T11:00:00Z',
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'task-1',
    projectId: 'proj-nexus-game',
    title: 'Verify session window tumbling logic for late event arrival',
    description: 'Ensure 5-second watermark delay correctly drops or redirects late game client events.',
    creatorId: 'usr-1',
    assigneeId: 'usr-1',
    priority: 'high',
    status: 'in_progress',
    dueDate: '2026-09-05T18:00:00Z',
    pipelineId: 'pipe-player-session-agg',
    labels: ['Streaming', 'Windowing', 'Quality'],
    subtasks: [
      { id: 'sub-1', title: 'Add unit tests for tumbling window bounds', completed: true },
      { id: 'sub-2', title: 'Simulate 10s out-of-order event timestamps', completed: false },
    ],
    createdAt: '2026-02-28T10:00:00Z',
    updatedAt: '2026-08-31T20:00:00Z',
  },
  {
    id: 'task-2',
    projectId: 'proj-nexus-game',
    title: 'Deploy ML Feature Set contract enforcement',
    description: 'Connect Quality Check Gate node to ds-player-features sink.',
    creatorId: 'usr-3',
    assigneeId: 'usr-3',
    priority: 'medium',
    status: 'done',
    dueDate: '2026-08-30T17:00:00Z',
    pipelineId: 'pipe-player-session-agg',
    datasetId: 'ds-player-features',
    labels: ['ML', 'Contracts'],
    subtasks: [
      { id: 'sub-3', title: 'Define minQualityScorePct = 98.0 in DataContract', completed: true },
    ],
    createdAt: '2026-02-25T09:00:00Z',
    updatedAt: '2026-08-30T17:00:00Z',
  },
];

export const INITIAL_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'aud-1',
    userId: 'usr-1',
    userName: 'Alex Mercer',
    userRole: 'Data Engineer',
    action: 'Pipeline published',
    resourceType: 'Pipeline',
    resourceId: 'pipe-player-session-agg',
    resourceName: 'Player Session & Churn Predictor Pipeline',
    timestamp: '2026-08-31T23:45:00Z',
    ipAddress: '127.0.0.1',
    createdAt: '2026-08-31T23:45:00Z',
    updatedAt: '2026-08-31T23:45:00Z',
  },
  {
    id: 'aud-2',
    userId: 'usr-2',
    userName: 'Elena Rostova',
    userRole: 'Game Analyst',
    action: 'Schema updated',
    resourceType: 'Schema',
    resourceId: 'sch-game-event',
    resourceName: 'GameTelemetryEvent',
    timestamp: '2026-08-28T09:00:00Z',
    ipAddress: '127.0.0.1',
    createdAt: '2026-08-28T09:00:00Z',
    updatedAt: '2026-08-28T09:00:00Z',
  },
];
